name: Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload to COS
      uses: zkqiang/tencent-cos-action@v0.1.0
      with:
        args: upload -r app/release/ igm/release/android/ && upload -r app/release/*.apk igm/release/android/com.bytemoe.parkingassistant-latest.apk
        secret_id: ${{ secrets.SECRET_ID }}
        secret_key: ${{ secrets.SECRET_KEY }}
        bucket: ${{ secrets.BUCKET }}
        region: ap-chongqing
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        path: app/release/*.apk
