name: Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          path: app/build/outputs/apk/release/*.apk
      - name: Upload to OSS (Version)
        uses: tvrcgo/upload-to-oss@v0.1.1
        with:
          key-id: ${{ secrets.OSS_ACCESS_ID }}
          key-secret: ${{ secrets.OSS_ACCESS_SECRET }}
          region: oss-cn-beijing
          bucket: cedt-beijing
          asset-path: app/build/outputs/apk/release/
          target-path: /igm/release/android/
      - name: Upload to OSS (Latest)
          uses: tvrcgo/upload-to-oss@v0.1.1
          with:
            key-id: ${{ secrets.OSS_ACCESS_ID }}
            key-secret: ${{ secrets.OSS_ACCESS_SECRET }}
            region: oss-cn-beijing
            bucket: cedt-beijing
            asset-path: app/build/outputs/apk/release/*.apk
            target-path: /igm/release/android/com.bytemoe.parkingassistant-latest.apk
      - name: Upload to COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -r app/build/outputs/apk/release/ igm/release/android/ && upload -r app/build/outputs/apk/release/*.apk igm/release/android/com.bytemoe.parkingassistant-latest.apk
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-chongqing
